package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Metric struct{ID int64 `json:"id"`;Name string `json:"name"`;Labels string `json:"labels"`;Type string `json:"type"`;Value float64 `json:"value"`;RecordedAt time.Time `json:"recorded_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"metrics.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS metrics(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,labels TEXT DEFAULT '',type TEXT DEFAULT 'gauge',value REAL NOT NULL,recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Record(m *Metric)error{res,err:=db.Exec(`INSERT INTO metrics(name,labels,type,value)VALUES(?,?,?,?)`,m.Name,m.Labels,m.Type,m.Value);if err!=nil{return err};m.ID,_=res.LastInsertId();return nil}
func(db *DB)Latest()([]map[string]interface{},error){rows,err:=db.Query(`SELECT name,labels,type,value,recorded_at FROM(SELECT name,labels,type,value,recorded_at,ROW_NUMBER()OVER(PARTITION BY name ORDER BY recorded_at DESC)rn FROM metrics)WHERE rn=1 ORDER BY name`);if err!=nil{return nil,err};defer rows.Close();var out[]map[string]interface{};for rows.Next(){var name,labels,typ string;var val float64;var ts time.Time;rows.Scan(&name,&labels,&typ,&val,&ts);out=append(out,map[string]interface{}{"name":name,"labels":labels,"type":typ,"value":val,"recorded_at":ts})};return out,nil}
func(db *DB)History(name string)([]Metric,error){rows,_:=db.Query(`SELECT id,name,labels,type,value,recorded_at FROM metrics WHERE name=? ORDER BY recorded_at DESC LIMIT 200`,name);defer rows.Close();var out[]Metric;for rows.Next(){var m Metric;rows.Scan(&m.ID,&m.Name,&m.Labels,&m.Type,&m.Value,&m.RecordedAt);out=append(out,m)};return out,nil}
func(db *DB)Stats()(map[string]interface{},error){var names,total int;db.QueryRow(`SELECT COUNT(DISTINCT name) FROM metrics`).Scan(&names);db.QueryRow(`SELECT COUNT(*) FROM metrics`).Scan(&total);return map[string]interface{}{"metric_names":names,"total_points":total},nil}
